version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: rails_boilerplate_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my_cnf:/etc/mysql/conf.d
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "4306:3306"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
