default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000create user karasu@localhost identified by 'crow'
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  database: rails_boilerplate_development

test:
  <<: *default
  database: rails_boilerplate_test

production:
  <<: *default
  database: rails_boilerplate_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
